# Generated by Django 3.1.1 on 2020-09-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('event', models.TextField(verbose_name='event')),
                ('used', models.BooleanField(verbose_name='used')),
            ],
        ),
    ]
