# Generated by Django 3.1.1 on 2020-09-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_datecollect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datecollect',
            name='id',
        ),
        migrations.AlterField(
            model_name='datecollect',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='date'),
        ),
    ]
