# Generated by Django 3.1.1 on 2020-09-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200912_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecollect',
            name='stored',
            field=models.BooleanField(default=False, verbose_name='events stored'),
        ),
    ]
